<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="">
<head>
  <title>Test Results Report - com.fanbei.login</title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name="description" content="TestNG unit test results." />
  <link href="reportng.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="reportng.js"></script>
</head>
<body>
<h1>com.fanbei.login</h1>
<p>
  Test duration: 1.119s
</p>



  <table class="resultsTable">
    <tr><th colspan="3" class="header failed">Failed Tests</th></tr>
          <tr>
        <td colspan="3" class="group">com.fanbei.login.GetUserInfoTest</td>
      </tr>
            
<tr>
  <td class="method">
                  GetUserInfo
      </td>
  <td class="duration">
    0.024s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">"", "1005", "用户不存在"</span><br />
    
        

        <a href="javascript:toggleElement('exception-0', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [1005] but found [1015]</b></a><br />
    <div class="stackTrace" id="exception-0">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              com.fanbei.login.GetUserInfoTest.GetUserInfo(GetUserInfoTest.java:54)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:696)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:348)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:254)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1149)<br />
              org.testng.TestNG.run(TestNG.java:1057)<br />
              org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  GetUserInfo
      </td>
  <td class="duration">
    0.027s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">"13656648511", "1005", "用户不存在"</span><br />
    
        

        <a href="javascript:toggleElement('exception-1', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [1005] but found [1015]</b></a><br />
    <div class="stackTrace" id="exception-1">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              com.fanbei.login.GetUserInfoTest.GetUserInfo(GetUserInfoTest.java:54)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:696)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:348)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:254)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1149)<br />
              org.testng.TestNG.run(TestNG.java:1057)<br />
              org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)<br />
                </div>
      </td>
</tr>
          <tr>
        <td colspan="3" class="group">com.fanbei.login.UserGetMineInfoTest</td>
      </tr>
            
<tr>
  <td class="method">
                  UserGetMineInfo
      </td>
  <td class="duration">
    0.033s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">"13656648511", "1005", "用户不存在"</span><br />
    
        

        <a href="javascript:toggleElement('exception-2', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [1005] but found [1015]</b></a><br />
    <div class="stackTrace" id="exception-2">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              com.fanbei.login.UserGetMineInfoTest.UserGetMineInfo(UserGetMineInfoTest.java:54)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:696)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:348)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:254)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1149)<br />
              org.testng.TestNG.run(TestNG.java:1057)<br />
              org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  UserGetMineInfo
      </td>
  <td class="duration">
    0.024s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">"", "1005", "用户不存在"</span><br />
    
        

        <a href="javascript:toggleElement('exception-3', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [1005] but found [1015]</b></a><br />
    <div class="stackTrace" id="exception-3">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              com.fanbei.login.UserGetMineInfoTest.UserGetMineInfo(UserGetMineInfoTest.java:54)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:696)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:348)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:254)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1149)<br />
              org.testng.TestNG.run(TestNG.java:1057)<br />
              org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)<br />
                </div>
      </td>
</tr>
          <tr>
        <td colspan="3" class="group">com.fanbei.login.UserLoginTest</td>
      </tr>
            
<tr>
  <td class="method">
                  UserLogin
      </td>
  <td class="duration">
    0.032s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">"1365664852", "dc483e80a7a0bd9ef71d8cf973673924", "ios10.3.2", "iPhone", "07BB9C6D-D587-4638-B569-EC83BC99A99E", "ewogICJ0b2tlbklkIiA6ICJUWXh2UzNZYUprQTNVZWF4eDhEU0JIanlabGNiMWhhNXUybTRVTENCWEtwTHFZMks2QmlvMjB3ZlNZNEJNd1krbTROcGNKSm9IYUkzZ2VLMEd1ZG9ldz09IiwKICAib3MiIDogImlPUyIsCiAgInByb2ZpbGVUaW1lIiA6IDc3OSwKICAidmVyc2lvbiIgOiAiMi4xLjUiCn0", "1005", "用户不存在"</span><br />
    
        

        <a href="javascript:toggleElement('exception-4', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [1005] but found [1015]</b></a><br />
    <div class="stackTrace" id="exception-4">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              com.fanbei.login.UserLoginTest.UserLogin(UserLoginTest.java:88)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:696)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:348)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:254)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1149)<br />
              org.testng.TestNG.run(TestNG.java:1057)<br />
              org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  UserLogin
      </td>
  <td class="duration">
    0.029s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">"11013656648", "dc483e80a7a0bd9ef71d8cf973673924", "ios10.3.2", "iPhone", "07BB9C6D-D587-4638-B569-EC83BC99A99E", "ewogICJ0b2tlbklkIiA6ICJUWXh2UzNZYUprQTNVZWF4eDhEU0JIanlabGNiMWhhNXUybTRVTENCWEtwTHFZMks2QmlvMjB3ZlNZNEJNd1krbTROcGNKSm9IYUkzZ2VLMEd1ZG9ldz09IiwKICAib3MiIDogImlPUyIsCiAgInByb2ZpbGVUaW1lIiA6IDc3OSwKICAidmVyc2lvbiIgOiAiMi4xLjUiCn0", "1005", "用户不存在"</span><br />
    
        

        <a href="javascript:toggleElement('exception-5', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [1005] but found [1015]</b></a><br />
    <div class="stackTrace" id="exception-5">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              com.fanbei.login.UserLoginTest.UserLogin(UserLoginTest.java:88)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:696)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:348)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:254)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1149)<br />
              org.testng.TestNG.run(TestNG.java:1057)<br />
              org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  UserLogin
      </td>
  <td class="duration">
    0.032s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">"", "dc483e80a7a0bd9ef71d8cf973673924", "ios10.3.2", "iPhone", "07BB9C6D-D587-4638-B569-EC83BC99A99E", "ewogICJ0b2tlbklkIiA6ICJUWXh2UzNZYUprQTNVZWF4eDhEU0JIanlabGNiMWhhNXUybTRVTENCWEtwTHFZMks2QmlvMjB3ZlNZNEJNd1krbTROcGNKSm9IYUkzZ2VLMEd1ZG9ldz09IiwKICAib3MiIDogImlPUyIsCiAgInByb2ZpbGVUaW1lIiA6IDc3OSwKICAidmVyc2lvbiIgOiAiMi4xLjUiCn0", "1005", "用户不存在"</span><br />
    
        

        <a href="javascript:toggleElement('exception-6', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [1005] but found [1015]</b></a><br />
    <div class="stackTrace" id="exception-6">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              com.fanbei.login.UserLoginTest.UserLogin(UserLoginTest.java:88)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:696)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:348)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:254)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1149)<br />
              org.testng.TestNG.run(TestNG.java:1057)<br />
              org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  UserLogin
      </td>
  <td class="duration">
    0.037s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">"13656648511", "dc483e80a7a0bd9ef71d8cf973673924", "ios10.3.2", "iPhone", "07BB9C6D-D587-4638-B569-EC83BC99A99E", "ewogICJ0b2tlbklkIiA6ICJUWXh2UzNZYUprQTNVZWF4eDhEU0JIanlabGNiMWhhNXUybTRVTENCWEtwTHFZMks2QmlvMjB3ZlNZNEJNd1krbTROcGNKSm9IYUkzZ2VLMEd1ZG9ldz09IiwKICAib3MiIDogImlPUyIsCiAgInByb2ZpbGVUaW1lIiA6IDc3OSwKICAidmVyc2lvbiIgOiAiMi4xLjUiCn0", "1005", "用户不存在"</span><br />
    
        

        <a href="javascript:toggleElement('exception-7', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [1005] but found [1015]</b></a><br />
    <div class="stackTrace" id="exception-7">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              com.fanbei.login.UserLoginTest.UserLogin(UserLoginTest.java:88)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:696)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:348)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:254)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1149)<br />
              org.testng.TestNG.run(TestNG.java:1057)<br />
              org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)<br />
                </div>
      </td>
</tr>
      </table>


  <table class="resultsTable">
    <tr><th colspan="3" class="header passed">Passed Tests</th></tr>
          <tr>
        <td colspan="3" class="group">com.fanbei.login.GetUserInfoTest</td>
      </tr>
            
<tr>
  <td class="method">
                  GetUserInfo
      </td>
  <td class="duration">
    0.056s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">"13656648524", "1000", "成功"</span><br />
    
        

      </td>
</tr>
          <tr>
        <td colspan="3" class="group">com.fanbei.login.UserGetMineInfoTest</td>
      </tr>
            
<tr>
  <td class="method">
                  UserGetMineInfo
      </td>
  <td class="duration">
    0.116s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">"13656648524", "1000", "成功"</span><br />
    
        

      </td>
</tr>
          <tr>
        <td colspan="3" class="group">com.fanbei.login.UserLoginTest</td>
      </tr>
            
<tr>
  <td class="method">
                  UserLogin
      </td>
  <td class="duration">
    0.707s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">"13656648524", "dc483e80a7a0bd9ef71d8cf973673924", "ios10.3.2", "iPhone", "07BB9C6D-D587-4638-B569-EC83BC99A99E", "ewogICJ0b2tlbklkIiA6ICJUWXh2UzNZYUprQTNVZWF4eDhEU0JIanlabGNiMWhhNXUybTRVTENCWEtwTHFZMks2QmlvMjB3ZlNZNEJNd1krbTROcGNKSm9IYUkzZ2VLMEd1ZG9ldz09IiwKICAib3MiIDogImlPUyIsCiAgInByb2ZpbGVUaW1lIiA6IDc3OSwKICAidmVyc2lvbiIgOiAiMi4xLjUiCn0", "1000", "成功"</span><br />
    
        

      </td>
</tr>
      </table>
  
</body>
</html>
